### ISSUE TITLE
Find or add deep extend utility

### ISSUE THREAD

**Issue by daviskoh** [inrhythm/vivace#118]

**Comment by jackofseattle** [comment]
I think this should work. ( really quick writing)

```js
function deepClone(obj)  {
    if (!obj || (typeof obj !== 'object')) return obj;  // by value
    let clone;
    if (Array.isArray(obj)) clone = Array.prototype.slice.call(obj);
    else if (obj.constructor!=={}.constructor) return obj; // by reference
    else clone = Object.assign({}, obj);
    for (var key in clone) {
        clone[key] = deepClone(clone[key]);
    }
    return clone;
}
``

**Comment by jshor** [comment]
we needed this for the merging of defaultScope with scope, but we took care of it - so is this still necessary?

**Comment by jackofseattle** [comment]
I think we'll be ok without this now
On Tue, Jan 19, 2016 at 14:16 Josh S. <notifications@github.com> wrote:

> we needed this for the merging of defaultScope with scope, but we took
> care of it - so is this still necessary?
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/inrhythm/vivace/issues/118#issuecomment-172956328>.
>

-- 
 InRhythm™ <http://www.inrhythm.com>  <http://www.inrhythm.com/> |  Services 
<http://inrhythm.com/resources/Brochure_Inrhythm.pdf> | Testimonials 
<http://inrhythm.com/testimonials.html>

494 8th Ave. Suite 1700 New York, NY 10001

*Accelerating product delivery *Follow Us <https://twitter.com/GetInRhythm>
