### ISSUE TITLE
Add ability to upload image for user

### ISSUE THREAD

**Issue by jackofseattle** [inrhythm/vivace#41]
- [x] Front End
- [x] Back End

**Comment by jshor** [comment]
I'll look into a drag-drop angular directive for uploading images. For the backend we'll convert the image to a base64 string for db storage.

**Comment by jackofseattle** [comment]
@jshor convert the image to base64 before sending to the server, it's easier and we don't have to worry about taxing our server with image processing.   https://developer.mozilla.org/en-US/docs/Web/API/FileReader/readAsDataURL
