### ISSUE TITLE
Add api for sending and retrieving candidate comments

### ISSUE THREAD

**Issue by jackofseattle** [inrhythm/vivace#73]
- [x] Add Comment
 - [x] Fetch List of Comments

**Comment by daviskoh** [comment]
The work for this was done in #63 (https://github.com/inrhythm/vivace/pull/74).

Given the size of that PR and how long it has been opened, I think it makes sense to have that merged in first and use this branch for testing. Thoughts?

**Comment by jackofseattle** [comment]
We can do that.
